model: 'LFR_DZ_CSTR'

doe: 'C:\Users\jacob\OneDrive - University of Louisville\Projects\Dissertation\PhaseI\data_analysis\TRANSONIC\TRANSONIC\data\CASE_PARAMETERS_MODEL.csv'

wd: 'C:\Users\jacob\OneDrive - University of Louisville\Projects\Dissertation\PhaseI\data_analysis\TRANSONIC\TRANSONIC\results\LFR_DZ_CSTR'

input: 'C:\Users\jacob\OneDrive - University of Louisville\Projects\Dissertation\PhaseI\data_analysis\TRANSONIC\TRANSONIC\data\C_curves'

parameters:
- 'alpha'
- 'beta'

parameter_bounds:
- [0.01, 0.99]
- [0.01, 0.99]
