model: 'LFR_DZ_CSTR'

doe: 'examples/stenosed_tube/DOE.csv'

wd: 'examples/stenosed_tube'

input: 'examples/stenosed_tube/raw_data/C_curves'

parameters:
- [0.01, 0.99]
- [0.01, 0.99]

parameter_bounds: 
- [0.01, 0.99]
- [0.01, 0.99]